### ISSUE TITLE
Better decimal rounding

### ISSUE THREAD

**Issue by Techn1x** [shipshapecode/ember-math-helpers#119]
The current round helper rounds to the nearest integer using `Math.round()`, it could be useful to have a helper that rounds to a given decimal point...

```handlebars
{{round a decimals=2}}
```

Good or bad idea?

**Comment by rwwagner90** [comment]
@Techn1x I could see that being useful. It's not supported by `Math.round` though.

**Comment by skeate** [comment]
It is supported (kind of) by `Number`, though. `(2.1254).toFixed(2) === '2.13'`. Unfortunately (depending on use case), it also adds zeroes: `(2).toFixed(2) === '2.00'`

**Comment by rwwagner90** [comment]
@skeate should we have the `round` helper use `Math.round` unless you pass `decimals`, and if you specify decimals use `toFixed`?

**Comment by Techn1x** [comment]
I wrote this helper few weeks ago to solve the issue for myself. However if you do something like `8.449` rounded to 1 decimal place, it returns 8.4 (whereas it should return 8.5) so it's not entirely correct, but if someone is clever enough to figure it out properly this might help;

```javascript
import { helper } from '@ember/component/helper';

// Rounding decimal places since it doesn't seem to exist as a js math function, or as an ember-math-helpers helper
// NOTE: This will currently only work for decimalPlaces >= 0, with some work negative values could probably be supported

export function roundDecimal([value,decimals]) {

	if(!value || decimals < 0) return value;
	if(!decimals || decimals === 0) return Math.round(value);
	
	var sign = '-';

	return Number(Math.round(value + 'e' + decimals) + 'e' + sign + decimals);
}

export default helper(roundDecimal);
```

**Comment by Techn1x** [comment]
Hopefully some combination of `Math.round()`, `Number.toFixed()` and my above code snippet will produce a correctly rounded result...

**Comment by skeate** [comment]
8.449 should round to 8.4. Rounding does not take into account anything past the number after the cutoff.

**Comment by rwwagner90** [comment]
@Techn1x @skeate either of you guys interested in submitting a PR for this?

**Comment by Techn1x** [comment]
@skeate oh haha my bad, you're right. Seems rounding is only supposed to look at the next number along  and that's it. That being said, `toFixed()` still doesn't seem to work right.
For example, here's some funky answers I got;
`(8.45).toFixed(1) === '8.4'` (incorrect, should be 8.5)
`(8.49).toFixed(1) === '8.5'` (correct)
`(8.65).toFixed(1) === '8.7'` (correct)

(Just to be 100% sure I am now using https://www.calculatorsoup.com/calculators/math/roundingnumbers.php for my rounding hahaha)

@rwwagner90 I can probably write a PR for this this weekend, if no-one beats me to it

**Comment by skeate** [comment]
That discrepancy is a result of the floating point representation of (e.g.) 8.45:
```
> 8.45 - 1
7.449999999999999
```
( - 1 because otherwise it'll just dutifully report "8.45")

There's a version that works here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round#Decimal_rounding
