### ISSUE TITLE
Update breaks Ember builds for Ember 3.7

### ISSUE THREAD

**Issue by Redsandro** [shipshapecode/ember-math-helpers#197]
I can't provide a range of versions so I don't know up until which version this error occurs, but for Ember 3.7 you'll need `ember-math-helpers` <= 2.10.0.

Ember installations with `ember-math-helpers` in `package.json` configured as ^2.10.0 will break when doing a fresh `npm install`. 

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-math-helpers]) in ember-math-helpers/helpers/abs.js

Cannot read property 'getHash' of null
```

**Comment by rwwagner90** [comment]
@Redsandro the tests are passing back to Ember 3.4 https://travis-ci.org/shipshapecode/ember-math-helpers, so I think there may be more at play here and/or there is something about 3.7 specifically that doesn't work.

**Comment by Redsandro** [comment]
@rwwagner90 Possibly. I can't figure out why this is happening though. Does the message _"Cannot read property 'getHash' of null"_ `ember-math-helpers/helpers/abs.js` give you any idea about where I should be looking?

**Comment by rwwagner90** [comment]
It does not. There is nothing in https://github.com/shipshapecode/ember-math-helpers/blob/master/addon/helpers/abs.js that uses anything called `getHash`. Is it possible to get a small, isolated reproduction we could look at? It's also possible there was a bug in Ember itself in 3.7. Would you be able to use 3.8?

**Comment by Redsandro** [comment]
Sorry for not getting back to you earlier. I was traveling. This is definitely still an issue and it's weird that I can get it to work by downgrading `ember-math-helpers`.

I'm a long time Linux user, but Ember feels a bit like Windows in the old days, where over time, updates cause more and more inexplicable errors to the point of needing a fresh install.

With [Ember Octane](https://blog.emberjs.com/2019/12/20/octane-is-here.html) out, I think it might be time to do a 'fresh install'.

I will close this issue for now.

**Comment by rwwagner90** [comment]
@Redsandro if you can reproduce in a small, self contained, app, let me know.

**Comment by iamareebjamal** [comment]
Happening for us as well

**Comment by rwwagner90** [comment]
@iamareebjamal can you provide any details? Ember version, ember-cli version, custom broccoli stuff you might be doing, etc?

**Comment by iamareebjamal** [comment]
"ember-cli": "~3.10.1"

Using broccoli-persistent-filter

The project is open source. This is the PR - https://github.com/fossasia/open-event-frontend/pull/3873

**Comment by rwwagner90** [comment]
My guess would be something with broccoli, babel, or the htmlbars update, but I don't really know. I've been using it without any issues in several projects. It might be that you are using broccoli-funnel and this addon is not compatible with the version or something. @Redsandro thoughts?

**Comment by Redsandro** [comment]
One guess is that a certain dependency is too new. But I'm grasping straws, I couldn't figure it out.

https://github.com/shipshapecode/ember-math-helpers/compare/v2.10.0...v2.11.0 see `package.json`

**Comment by iamareebjamal** [comment]
It's working for 2.11.1 for us. Breaking on latest

**Comment by iamareebjamal** [comment]
Starts breaking from 2.11.2

**Comment by rwwagner90** [comment]
@iamareebjamal no real changes between those two versions, except maybe ember-cli-babel version https://github.com/shipshapecode/ember-math-helpers/compare/v2.11.1...v2.11.2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32

Unless you are perhaps using node older than 8.x? We did drop support for node 6 there.

**Comment by iamareebjamal** [comment]
Node 12. There are other dependency updates as well. But yes, no such code change. Nevertheless, for some reason, babel can't find this module for hashing

**Comment by Redsandro** [comment]
Is it relevant that 

* I was using Ember 3.7 and the update broke when emh updated dependency `ember-source` from `3.7` to `3.9`
* @iamareebjamal was using Ember 3.10 and emh `2.11.1` had dependency `ember-source` `3.9` updated to `3.15` in latest?

Perhaps ember-source used breaks compatibility with older versions of Ember?

**Comment by rwwagner90** [comment]
@Redsandro no ember-source is a devDep and does not get shipped.

**Comment by Redsandro** [comment]
Yeah makes sense. It's puzzling.

So this issue is now confirmed, but it's hard to figure out why it is occurring. It could very well be an upstream issue, but so far the only plugin that I encountered needed special care (trial and error) when upgrading was `ember-math-helper`. Because the usual problem for other plugins is the other way around: newer Ember version might break them.

I figured it was easiest to reinstall a fresh copy of everything without upgrading for my app and then copy over the relevant files (and edit where necessary).

**Comment by rwwagner90** [comment]
It's likely the custom whitelist / blacklist stuff we provide, so you don't have to ship all the helpers. That's the only thing different than any standard addon. I mostly copied it from here https://github.com/DockYard/ember-composable-helpers/blob/master/index.js so maybe we should update things to match theirs more closely and see if it helps.

**Comment by rwwagner90** [comment]
Can you guys try 2.13.0 and see if anything is different?

**Comment by iamareebjamal** [comment]
When we upgraded rest of our dependencies, including the handlebars one, it automatically started working for us, the previous version as well. Unfortunately, that was a busy week and we couldn't notice exactly which dependency upgrade fixed it

**Comment by Redsandro** [comment]
2.13.0 works for me on a different app. I am not be able to check the exact same app with the exact same dependencies that had the issue in the fist place, because that one had since been upgraded from Ember 3.7. 

Thank you again @rwwagner90 for looking into this.
