### ISSUE TITLE
only/except not working for app tree

### ISSUE THREAD

**Issue by simonihmig** [shipshapecode/ember-math-helpers#242]
Although i have "only" `add`, `mult` and `sub`, all the reexports of the addon's app tree are visible in the consuming app: 

![image](https://user-images.githubusercontent.com/1325249/77189148-67c99b00-6ad7-11ea-86a8-29d77ebe082d.png)

Note: the actual helpers in the addon tree seem to be correctly filtered. 

I'll see if I can come up with a PR...

**Comment by simonihmig** [comment]
Oh, never mind. Seems that was already fixed in #237!

@rwwagner90 Mind cutting a release?

**Comment by rwwagner90** [comment]
@simonihmig sure thing! Will cut a release shortly.
