### ISSUE TITLE
Score on Ember Observer is Wonky

### ISSUE THREAD

**Issue by djsegal** [shipshapecode/ember-math-helpers#4]
------

##### ember-math-helpers currently has a 6/10 on [Ember Observer](https://emberobserver.com/addons/ember-math-helpers).

+ I think it's pretty easy to fix. It looks like the contents in **`Box A`** should be moved to **`Box B`**

+ This should fix the error described in **`Box C`** and get you up to a **8+**/10

------

<img width="1332" alt="screen shot 2016-04-22 at 12 44 07 pm" src="https://cloud.githubusercontent.com/assets/3156114/14748591/7e8fc036-0888-11e6-87d8-d0cf25c1d8ff.png">

**Comment by rwwagner90** [comment]
Hi @djsegal I did update the repo in package.json, but I don't think I deployed to npm again after that. I'm going ahead and bumping the version and publishing again. Hopefully it fixes it.

**Comment by djsegal** [comment]
Nice! You moved up to an 8!

**Comment by rwwagner90** [comment]
Thanks for bringing this to my attention!
