### ISSUE TITLE
Any plans to add`sum` helper?

### ISSUE THREAD

**Issue by balinterdi** [shipshapecode/ember-math-helpers#40]
I think having this could be useful:

```handlebars
(sum sectionTotal1 sectionTotal2)
```

**Comment by skeate** [comment]
Is there any appreciable difference between that and `add`?

**Comment by balinterdi** [comment]
@skeate No, there is none, I just did not see the `add` helper, sorry :)

**Comment by brandonjmckay** [comment]
@skeate, can you use the `add` helper for an array? `{{add thisItem.arrayOfNumbers}}`

A sum helper would be great for this, if `add` doesn't already do this.

**Comment by brandonjmckay** [comment]
I just tried this with [`ember-composable-helpers`](https://github.com/DockYard/ember-composable-helpers), the following didn't work:

```
{{add (map-by 'clientPriceCents' order.orderItems)}}
```

Going to look to see if there is a splat helper of some kind to

**Comment by brandonjmckay** [comment]
If I make a PR, would it be welcomed?

**Comment by skeate** [comment]
This would be trivial with a spread operator, which is in RFC: https://github.com/emberjs/rfcs/issues/184

though that appears to be more focused on named arguments, and thus (if they don't see a use case for it) might not be implemented to support arrays.

I still don't agree with adding a separate `sum` helper, especially if it's not just an alias to `add`. Having to check the docs all the time to remember which was which would be a pain.

This should be doable with ember-composable-helpers, though. Perhaps `{{reduce add (map-by 'clientPriceCents' order.orderItems}}`? (can't test right now to see if that actually works)

One possibility for this addon would be to just do some typechecking. If we have one param and it's an array, return the sum of that. That does lead to "well why not flatten any arrays passed", and suddenly we're in space where behavior is not completely intuitive.

**Comment by brandonjmckay** [comment]
I was trying to test this out, but couldn't get it to work as you mentioned. Shelfing it for now though as I no longer need it for my use-case.
Thanks for the ideas! Hopefully it'll help people looking to do the same :)
