### ISSUE TITLE
Release doc for 2.x

### ISSUE THREAD

**Issue by ming-codes** [shipshapecode/ember-math-helpers#61]
Hi! Is there any release doc for 2.x release?

**Comment by rwwagner90** [comment]
Hi @ming-codes, no, there is no changelog or anything. What info are you looking for?

**Comment by ming-codes** [comment]
I was going through my project for dependency upgrade, then noticed a major version bump on `ember-math-helpers`. What's changed?

**Comment by rwwagner90** [comment]
@ming-codes I mostly just added all `Math` methods. There should be no breaking changes. You can compare https://github.com/shipshapecode/ember-math-helpers/tree/v2.0.0 and https://github.com/shipshapecode/ember-math-helpers/tree/v1.4.1 if you would like to see what changed in the 2.0 release. Please let me know if you have any specific questions.
