### ISSUE TITLE
Missing floor & ceil

### ISSUE THREAD

**Issue by djsegal** [shipshapecode/ember-math-helpers#8]
If division is possible, floor and ceil should be present

granted rounding has some difficulty (what to do at xxx.5 and whether to do account rounding)

**Comment by rwwagner90** [comment]
Hi @djsegal!

What do you mean? You'd like to see floor and ceil helpers added or you'd like to see rounding automatically applied when doing division?

**Comment by djsegal** [comment]
Floor and ceil helpers
