### ISSUE TITLE
dependencies vs devDependencies

### ISSUE THREAD

**Issue by lordblendi** [shipshapecode/ember-math-helpers#92]
Hi!

I installed this addon in an ember-addon with `ember install ember-math-helpers`. It put it under the `devDependencies` section of the package.json. When I tried to run my application it couldn't find the helpers. If I put it under `dependencies` and do an `npm install` again, it works. Should the ember install handle this by default?

**Comment by skeate** [comment]
The [CLI addon docs](https://ember-cli.com/extending/#addons-depending-on-other-addons) seem to indicate that's a intended to be a manual process. I guess it (currently) has no way of knowing whether it's something you actually want your addon to require in any other Ember app that uses it or not.

**Comment by lordblendi** [comment]
Okay, thank you!

**Comment by rwwagner90** [comment]
@lordblendi I believe you can do `ember install ember-math-helpers --save` to put in deps instead. If that doesn't work, I know how to implement that, so please give it a try and let me know if it works!

**Comment by lordblendi** [comment]
@rwwagner90  yes, that solved it, thank you!
